create_interface interface_1

set_property IOSTANDARD LVCMOS18 [get_ports Cin]
set_property PACKAGE_PIN H22 [get_ports Cin]

set_property IOSTANDARD LVCMOS18 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cout]
set_property PACKAGE_PIN F22 [get_ports {A[0]}]
set_property PACKAGE_PIN G22 [get_ports {A[1]}]
set_property PACKAGE_PIN H22 [get_ports {A[2]}]
set_property PACKAGE_PIN F21 [get_ports {A[3]}]
set_property PACKAGE_PIN H19 [get_ports {B[0]}]
set_property PACKAGE_PIN H18 [get_ports {B[1]}]
set_property PACKAGE_PIN H17 [get_ports {B[2]}]
set_property PACKAGE_PIN M15 [get_ports {B[3]}]
set_property PACKAGE_PIN V22 [get_ports cout]
set_property PACKAGE_PIN T22 [get_ports {s[0]}]
set_property PACKAGE_PIN T21 [get_ports {s[1]}]
set_property PACKAGE_PIN U22 [get_ports {s[2]}]
set_property PACKAGE_PIN U21 [get_ports {s[3]}]
create_interface interface_2
